#!/bin/bash

choices="$(dialog --stdout --checklist "Update" 0 0 0 \
  1 "update system" off \
  2 "update containers" off \
  3 "prune docker images" off)"

for choice in ${choices}; do
  case ${choice} in
    1)
      arch="$(command -v yay)"
      debian="$(command -v apt)"
      if [ ! $arch == "" ]
      then
        yay -Syu
      elif [ ! $debian == "" ]
      then
        sudo apt update && sudo apt upgrade
      fi
      ;;

    2)
      cd ~/docker
      docker-compose pull
      docker-compose up -d
      ;;

    3)
      docker image prune
  esac;
done
