#!/bin/bash

choices="$(dialog --stdout --checklist "Update" 0 0 0 \
  1 "update system" on \
  2 "update containers" on \
  3 "prune docker images" on \
  4 "reboot" off )"

LSBLK=$(lsblk -S)

for choice in ${choices}; do
  case ${choice} in
    1)
      ARCH="$(command -v yay)"
      DEBIAN="$(command -v apt)"
      if [[ -n $ARCH ]]
      then
        yay -Syu
      elif [[ -n $DEBIAN ]]
      then
        sudo apt update && sudo apt upgrade
      fi
      ;;

    2)
      cd ~/docker
      if [[ -n $LSBLK ]]; then
        docker-compose pull
      else
        docker-compose pull --no-parallel
      fi
      docker-compose up -d
      ;;

    3)
      docker image prune
      ;;

    4)
      sudo systemctl reboot
      ;;
  esac;
done
