#!/bin/bash

choices="$(dialog --stdout --checklist "Update" 0 0 0 \
  1 "update system" on \
  2 "update containers" on \
  3 "prune docker images" on \
  4 "reboot" off )"

for choice in ${choices}; do
  case ${choice} in
    1)
      arch="$(command -v yay)"
      debian="$(command -v apt)"
      if [ ! $arch == "" ]
      then
        yay -Syu
      elif [ ! $debian == "" ]
      then
        sudo apt update && sudo apt upgrade
      fi
      ;;

    2)
      cd ~/docker
      docker-compose pull --no-parallel
      docker-compose up -d
      ;;

    3)
      docker image prune
      ;;

    4)
      sudo systemctl reboot
      ;;
  esac;
done
