#!/bin/bash

# Variables
HOME="/home/bradley"
DOTFILES="/home/bradley/dotfiles"

# i3 & i3status
cp $HOME/.config/i3/config $DOTFILES/i3.conf
cp $HOME/.config/i3status/config $DOTFILES/i3status.conf

# tmux
cp $HOME/.tmux.conf $DOTFILES/

# vimrc
cp $HOME/.vimrc $DOTFILES/

# bashrc
cp $HOME/.bashrc $DOTFILES/

# bash aliases
cp $HOME/.bash_aliases $DOTFILES/
