#!/bin/bash

LYFILE=${1?Error: No file given}
LYOUTPUT="${LYFILE%.*}"

lilypond -ddelete-intermediate-files=#t --png -dresolution=300 -o $LYOUTPUT\_web -danti-alias-factor=1 $LYFILE

# Clean-up
rm *.eps
rm *.texi
rm *.count
rm *.pdf
rm *.tex
